import fs from 'fs';
import path from 'path';

function getLanguage(filePath: string): 'php' | 'css' | 'js' | 'json' | 'markdown' | 'svg' | 'txt' {
  if (filePath.endsWith('.php')) return 'php';
  if (filePath.endsWith('.css')) return 'css';
  if (filePath.endsWith('.js')) return 'js';
  if (filePath.endsWith('.json')) return 'json';
  if (filePath.endsWith('.md')) return 'markdown';
  if (filePath.endsWith('.svg')) return 'svg';
  return 'txt';
}

function getPackage(filePath: string): 'core' | 'theme' | 'docs' {
  if (filePath.startsWith('hackersshikkhok-core/')) return 'core';
  if (filePath.startsWith('hackersshikkhok-theme/')) return 'theme';
  return 'docs';
}

function walkDir(dir: string, baseDir: string = dir): string[] {
  let results: string[] = [];
  const list = fs.readdirSync(dir);
  list.forEach((file) => {
    const fullPath = path.resolve(dir, file);
    const stat = fs.statSync(fullPath);
    if (stat && stat.isDirectory()) {
      results = results.concat(walkDir(fullPath, baseDir));
    } else {
      results.push(path.relative(baseDir, fullPath));
    }
  });
  return results;
}

async function sync() {
  console.log('Generating complete virtual file list from physical disk...');

  const roots = ['hackersshikkhok-core', 'hackersshikkhok-theme', 'hackersshikkhok-docs'];
  const allFiles: any[] = [];

  for (const root of roots) {
    const rootPath = path.resolve(process.cwd(), root);
    if (fs.existsSync(rootPath)) {
      const relPaths = walkDir(rootPath, process.cwd());
      for (const relPath of relPaths) {
        const full = path.resolve(process.cwd(), relPath);
        const content = fs.readFileSync(full, 'utf8');
        allFiles.push({
          path: relPath,
          package: getPackage(relPath),
          language: getLanguage(relPath),
          updatedAt: '2026-10-02',
          content,
        });
      }
    }
  }

  const tsContent = `// Hackers শিক্ষক (HackersShikkhok.com) — Virtual WordPress File Tree Registry
// Autogenerated and synchronized with physical files

import JSZip from 'jszip';

export interface VirtualFile {
  path: string;
  content: string;
  package: 'core' | 'theme' | 'docs';
  language: 'php' | 'css' | 'js' | 'javascript' | 'json' | 'markdown' | 'svg' | 'txt';
  updatedAt: string;
}

export type WpVirtualFile = VirtualFile;

export const PLUGIN_ICON_IMG = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 128 128'><rect width='128' height='128' rx='24' fill='%23050b14'/><path d='M64 16L24 36v32c0 28 40 44 40 44s40-16 40-44V36L64 16z' fill='none' stroke='%2300f5d4' stroke-width='6'/><text x='64' y='74' font-family='monospace' font-size='28' font-weight='bold' fill='%2300f5d4' text-anchor='middle'>HS</text></svg>";

export const PLUGIN_BANNER_IMG = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 772 250'><rect width='772' height='250' fill='%23050b14'/><text x='386' y='135' font-family='system-ui, sans-serif' font-size='32' font-weight='bold' fill='%2300f5d4' text-anchor='middle'>HACKERS শিক্ষক CORE</text></svg>";

export const THEME_SCREENSHOT_IMG = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 900'><rect width='1200' height='900' fill='%23050b14'/><text x='600' y='460' font-family='system-ui, sans-serif' font-size='56' font-weight='900' fill='%2300f5d4' text-anchor='middle'>HACKERS শিক্ষক THEME</text></svg>";

export async function generateAndDownloadZip(
  files: VirtualFile[],
  pkg: 'theme' | 'core' | 'docs' | 'all'
): Promise<{ fileName: string; fileCount: number; sizeBytes: number }> {
  const zip = new JSZip();
  const filterPkg = pkg === 'all' ? null : pkg;

  const targetFiles = filterPkg ? files.filter(f => f.package === filterPkg) : files;

  targetFiles.forEach((file) => {
    zip.file(file.path, file.content);
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  const fileName = pkg === 'core' 
    ? 'hackersshikkhok-core.zip' 
    : (pkg === 'theme' ? 'hackersshikkhok-theme.zip' : (pkg === 'docs' ? 'hackersshikkhok-docs.zip' : 'hackersshikkhok-complete.zip'));

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return {
    fileName,
    fileCount: targetFiles.length,
    sizeBytes: blob.size,
  };
}

export const INITIAL_VIRTUAL_FILES: VirtualFile[] = ${JSON.stringify(allFiles, null, 2)};
`;

  fs.writeFileSync(path.resolve(process.cwd(), 'src/data/wpVirtualFiles.ts'), tsContent, 'utf8');
  console.log(`Successfully generated and synced ${allFiles.length} files into wpVirtualFiles.ts!`);
}

sync().catch(err => {
  console.error(err);
  process.exit(1);
});
